### ISSUE TITLE
No tests detected at all if used with Spock-2.0-M3

### ISSUE THREAD

**Issue by szpak** [szpak/spock-global-unroll#7]
After upgrade Spock from 2.0-M2 to 2.0-M3 I noticed (thanks to that [workaround](https://github.com/gradle/gradle/issues/7452#issue-371613944)!) that Spock tests stopped to be detected. It wasn't obvious at the first as there was no error, but the debug logging shows:

```
[DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
[DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: Gradle Test Executor 14.
[DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
[INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'Gradle Test Executor 14'
[DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
[DEBUG] [TestEventLogger] 
[DEBUG] [TestEventLogger] Gradle Test Executor 14 STARTED
[DEBUG] [TestEventLogger] 
[DEBUG] [TestEventLogger] Gradle Test Executor 14 FAILED
[DEBUG] [TestEventLogger]     org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 14.
[DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:63)
[DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[DEBUG] [TestEventLogger]         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
[DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
[DEBUG] [TestEventLogger]         at com.sun.proxy.$Proxy2.stop(Unknown Source)
[DEBUG] [TestEventLogger]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
[DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[DEBUG] [TestEventLogger]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[DEBUG] [TestEventLogger]         at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
[DEBUG] [TestEventLogger]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
[DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
[DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
[DEBUG] [TestEventLogger]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
[DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[DEBUG] [TestEventLogger]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[DEBUG] [TestEventLogger]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
[DEBUG] [TestEventLogger]         at java.base/java.lang.Thread.run(Thread.java:832)
[DEBUG] [TestEventLogger] 
[DEBUG] [TestEventLogger]         Caused by:
[DEBUG] [TestEventLogger]         org.junit.platform.commons.JUnitException: TestEngine with ID 'spock' failed to discover tests
[DEBUG] [TestEventLogger]             at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:104)
[DEBUG] [TestEventLogger]             at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:81)
[DEBUG] [TestEventLogger]             at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:83)
[DEBUG] [TestEventLogger]             at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:66)
[DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
[DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
[DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
[DEBUG] [TestEventLogger]             at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
[DEBUG] [TestEventLogger]             ... 25 more
[DEBUG] [TestEventLogger] 
[DEBUG] [TestEventLogger]             Caused by:
[DEBUG] [TestEventLogger]             java.lang.NoSuchMethodError: 'void org.spockframework.runtime.extension.builtin.UnrollExtension.visitSpecAnnotation(spock.lang.Unroll, org.spockframework.runtime.model.SpecInfo)'
[DEBUG] [TestEventLogger]                 at info.solidsoft.spock.unroll.SpockGlobalUnrollExtension.visitSpec(SpockGlobalUnrollExtension.java:46)
[DEBUG] [TestEventLogger]                 at org.spockframework.runtime.ExtensionRunner.runGlobalExtensions(ExtensionRunner.java:46)
[DEBUG] [TestEventLogger]                 at org.spockframework.runtime.ExtensionRunner.run(ExtensionRunner.java:40)
[DEBUG] [TestEventLogger]                 at org.spockframework.runtime.SpockEngineDiscoveryPostProcessor.processSpecNode(SpockEngineDiscoveryPostProcessor.java:48)
[DEBUG] [TestEventLogger]                 at org.spockframework.runtime.SpockEngineDiscoveryPostProcessor.lambda$postProcessEngineDescriptor$0(SpockEngineDiscoveryPostProcessor.java:15)
[DEBUG] [TestEventLogger]                 at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[DEBUG] [TestEventLogger]                 at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[DEBUG] [TestEventLogger]                 at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[DEBUG] [TestEventLogger]                 at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[DEBUG] [TestEventLogger]                 at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[DEBUG] [TestEventLogger]                 at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[DEBUG] [TestEventLogger]                 at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[DEBUG] [TestEventLogger]                 at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[DEBUG] [TestEventLogger]                 at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[DEBUG] [TestEventLogger]                 at org.spockframework.runtime.SpockEngineDiscoveryPostProcessor.postProcessEngineDescriptor(SpockEngineDiscoveryPostProcessor.java:16)
[DEBUG] [TestEventLogger]                 at org.spockframework.runtime.SpockEngine.discover(SpockEngine.java:30)
[DEBUG] [TestEventLogger]                 at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:96)
[DEBUG] [TestEventLogger]                 ... 32 more
[DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: SUCCEEDED
[DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'Gradle Test Executor 14' finished with exit value 0 (state: SUCCEEDED)
[DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.17.74 completed (1 worker(s) in use)
```

That method was in fact removed (renamed) in 2.0-M3. spock-global-unroll is no longer needed with 2.0-M3+ as it natively support feature unrolling. However, it should fail with a meaningful error message, not just success with no tests detected...

However, after a talk with Marc Phillip in the past, it should [start](https://github.com/gradle/gradle/pull/12489) to fail with some meaningful error message in Gradle 6.4+. However, the above problem is not visible while tested with Gradle 6.5. I will try to investigate it.

**Comment by szpak** [comment]
Trying to generate MRE, I've noticed that throwing an exception if no tests are found hides the original reason why JUnit Platform (or rather the engine) failed to detect tests. With the exception throwing removed (e.g. changed to warning) there is just one failing test with the aforementioned stacktrace. I will raise it in https://github.com/gradle/gradle/issues/7452.
